version: "3.8"

services:
  api:
    build: 
      context: ./server
      args:   
        - platform='linux/amd64'
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - ./server:/usr/src/
    ports:
      - 8000:8000